// ===================================================
// UtsavMitra - Shared Constants & Cultural Intelligence
// ===================================================

import { CulturalTradition, EventType } from './types';

export const INDIAN_CITIES = [
  'Jaipur',
  'Delhi',
  'Mumbai',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Lucknow',
  'Ahmedabad',
  'Pune',
  'Udaipur',
  'Varanasi',
  'Goa',
  'Chandigarh',
  'Kochi',
] as const;

export const EVENT_TYPES: EventType[] = [
  'Wedding',
  'Engagement',
  'Reception',
  'Birthday',
  'Anniversary',
  'Baby Shower',
  'Naming Ceremony',
  'Housewarming',
  'Traditional Ceremony',
  'Corporate Event',
  'College Event',
  'Festival',
  'Religious Event',
  'Private Party',
  'Other',
];

export const CULTURAL_TRADITIONS: CulturalTradition[] = [
  'North Indian',
  'South Indian',
  'Bengali',
  'Punjabi',
  'Gujarati',
  'Rajasthani',
  'Marathi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayali',
  'Custom',
];

export const CULTURAL_THEMES_METADATA: Record<
  CulturalTradition,
  {
    themeColor: string;
    secondaryColor: string;
    accentColor: string;
    greetingShloka: string;
    englishGreeting: string;
    recommendedDecor: string;
    specialDishes: string[];
    musicHighlights: string[];
    dressCodeSuggestion: string;
    keyRituals: string[];
  }
> = {
  'Rajasthani': {
    themeColor: '#7A1F2B',
    secondaryColor: '#F4A340',
    accentColor: '#C9A227',
    greetingShloka: 'खम्मा घणी सा | पधारो म्हारे देस',
    englishGreeting: 'Auspicious union blessed with Royal Rajasthani heritage and warmth.',
    recommendedDecor: 'Royal Haveli courtyard, Bandhani drapes, brass urlis with marigolds, Diya lamps.',
    specialDishes: ['Dal Baati Churma', 'Gatte ki Sabzi', 'Ker Sangri', 'Mawa Kachori', 'Ghevar with Rabri'],
    musicHighlights: ['Manganiyar & Langa folk troupe', 'Nagada & Shehnai', 'Royal Ghoomar'],
    dressCodeSuggestion: 'Royal Bandhgala, Sherwani with Safa, Leheriya & Poshak sarees.',
    keyRituals: ['Ganesh Sthapana', 'Bhaat Nyotana', 'Pithi Dastoor', 'Saat Phere under Mandap'],
  },
  'South Indian': {
    themeColor: '#800020',
    secondaryColor: '#FFB800',
    accentColor: '#D4AF37',
    greetingShloka: 'मंगलम् भगवान् विष्णुः मङ्गलम् गरुडध्वजः',
    englishGreeting: 'Celebrating divine traditions, temple sacredness, and timeless blessings.',
    recommendedDecor: 'Fresh Jasmine & Marigold floral chandeliers, banana stem pillars, traditional Kuthuvilakku brass lamps.',
    specialDishes: ['Traditional Banana Leaf Feast', 'Bisi Bele Bath', 'Mysore Pak', 'Elaneer Payasam', 'Filter Kaapi'],
    musicHighlights: ['Nadaswaram & Thavil orchestra', 'Carnatic fusion violin', 'Classical Veena'],
    dressCodeSuggestion: 'Pure Kanjeevaram Silk sarees with temple jewelry, Pattu Veshti with Angavastram.',
    keyRituals: ['Kashi Yatra', 'Maalai Maatral', 'Kanyadaanam', 'Sapthapadi', 'Oonjal'],
  },
  'Bengali': {
    themeColor: '#990000',
    secondaryColor: '#FF9933',
    accentColor: '#FFD700',
    greetingShloka: 'শুভ পরিণয় | আনন্দ ও আশীর্বাদের উৎসব',
    englishGreeting: 'An enchanting celebration infused with fragrant Chandan, Shankha sounds, and love.',
    recommendedDecor: 'Alpana floor art, red-and-white themed floral mandap, Mukut motifs, clay pots.',
    specialDishes: ['Kolkata Biryani', 'Chhanar Dalna', 'Dhokar Dalna', 'Mishti Doi', 'Rosogolla & Sandesh'],
    musicHighlights: ['Rabindra Sangeet strings', 'Dhaak beats', 'Shehnai melody'],
    dressCodeSuggestion: 'Red & Gold Baluchari / Banarasi saree with Topor/Mukut, Kurta Dhoti with Uttoriyo.',
    keyRituals: ['Gaye Holud', 'Saat Paak', 'Subho Drishti', 'Mala Badal', 'Sindoor Daan'],
  },
  'Punjabi': {
    themeColor: '#8B0000',
    secondaryColor: '#FF7F00',
    accentColor: '#E5C158',
    greetingShloka: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ | ਰੱਬ ਦੀ ਮਿਹਰ ਨਾਲ ਖੁਸ਼ੀਆਂ ਦਾ ਤਿਉਹਾਰ',
    englishGreeting: 'High-energy celebration filled with vibrant colors, dhol beats, and heartfelt hospitality.',
    recommendedDecor: 'Phulkari draping, fairy light arches, kaleidoscope floral stage, colorful bangles installation.',
    specialDishes: ['Amritsari Kulcha', 'Dal Makhani', 'Paneer Tikka', 'Sarson da Saag', 'Pista Kulfi Falooda'],
    musicHighlights: ['Live Punjabi Dholis', 'Bhangra Troupe', 'Bollywood & Sufi Live Band'],
    dressCodeSuggestion: 'Heavily embroidered Lehenga, Patiala Suit, Designer Kurta Pajama with colorful Pagri.',
    keyRituals: ['Roka', 'Chooda & Kaleere', 'Sehrabandi', 'Baraat with Dhol', 'Anand Karaj / Pheras'],
  },
  'Gujarati': {
    themeColor: '#722F37',
    secondaryColor: '#FA8072',
    accentColor: '#DAA520',
    greetingShloka: 'માંગલિક પ્રસંગે આપનું હાર્દિક સ્વાગત છે',
    englishGreeting: 'Joyous festivities embracing Garba rhythms, warm hospitality, and festive colors.',
    recommendedDecor: 'Mirror-work Bandhani backdrop, Dandiya display, marigold floral curtains.',
    specialDishes: ['Gujarati Thali', 'Undhiyu', 'Dhokla', 'Khandvi', 'Shrikhand & Basundi'],
    musicHighlights: ['Live Garba & Dandiya Raas Orchestra', 'Sanedo live singing'],
    dressCodeSuggestion: 'Chaniya Choli with mirror embroidery, Kedia and Kurta with Nehru jacket.',
    keyRituals: ['Mandap Mahurat', 'Grah Shanti', 'Mosalu/Mameru', 'Jaimala', 'Hastamelap'],
  },
  'North Indian': {
    themeColor: '#7A1F2B',
    secondaryColor: '#F4A340',
    accentColor: '#C9A227',
    greetingShloka: 'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ | निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा',
    englishGreeting: 'A grand celebration uniting families with timeless customs, feasts, and joy.',
    recommendedDecor: 'Grand royal palace stage, crystal chandeliers, red rose and marigold cascades.',
    specialDishes: ['Shahi Paneer', 'Dal Bukhara', 'Naan & Kulchas', 'Gulab Jamun with Rabri', 'Live Chaat Counter'],
    musicHighlights: ['Sufi Ensemble', 'Live Bollywood Band', 'Royal Shehnai'],
    dressCodeSuggestion: 'Classic Sherwani with stole, Zardozi Lehenga Choli with Polki jewelry.',
    keyRituals: ['Ganesh Puja', 'Haldi & Mehndi', 'Sangeet Night', 'Baraat & Varmala', 'Phere'],
  },
  'Marathi': {
    themeColor: '#6B1D2F',
    secondaryColor: '#FFA500',
    accentColor: '#D4AF37',
    greetingShloka: 'शुभमंगल सावधान | मंगलमय प्रसंगी आपले सहर्ष स्वागत',
    englishGreeting: 'Simplicity, deep devotion, and vibrant Maharashtrian cultural warmth.',
    recommendedDecor: 'Traditional Mundavalya motifs, Marigold torans, Chhatrapati-inspired wooden arches.',
    specialDishes: ['Puran Poli with Ghee', 'Bharli Vangi', 'Masale Bhaat', 'Solkadhi', 'Shrikhand Puri'],
    musicHighlights: ['Tutari & Sanai', 'Dhol Tasha Pathak', 'Natya Sangeet acoustics'],
    dressCodeSuggestion: 'Paithani Nauvari saree with Kolhapuri Saaj, Dhoti Kurta with Pheta turban.',
    keyRituals: ['Sakharpuda', 'Kelvan', 'Halad Chadavane', 'Antarpat & Mangalashtak', 'Kanyadaan'],
  },
  'Tamil': {
    themeColor: '#781528',
    secondaryColor: '#E67E22',
    accentColor: '#C5A059',
    greetingShloka: 'நல்வரவு | மங்கல நிகழ்விற்கு அன்போடு வரவேற்கிறோம்',
    englishGreeting: 'Vedic harmony, fragrant jasmines, and divine temple traditions.',
    recommendedDecor: 'Malli poo (Jasmine) hangings, brass diyas, temple gopuram stage structure.',
    specialDishes: ['Traditional Tam Brahm Wedding Feast', 'Sambar Rice', 'Vatha Kuzhambu', 'Adhirasam', 'Payasam'],
    musicHighlights: ['Traditional Nadaswaram', 'Panchavadyam rhythm', 'Classical Carnatic vocalists'],
    dressCodeSuggestion: 'Madisar / Muhurtham Kanjivaram silk saree, Veshti and Angavastram with zari border.',
    keyRituals: ['Vratham', 'Janavasam', 'Kashi Yatra', 'Kanyadaanam', 'Muhurtham'],
  },
  'Telugu': {
    themeColor: '#80182A',
    secondaryColor: '#FF9E1B',
    accentColor: '#D4AF37',
    greetingShloka: 'శుభమస్తు | మా వివాహ మహోత్సవానికి సాదర స్వాగతం',
    englishGreeting: 'Celebrating sacred union with Jeelakarra Bellam, talambralu, and royal grandeur.',
    recommendedDecor: 'Lotus mandap, yellow marigold pillars, peacock brass sculptures.',
    specialDishes: ['Gutti Vankaya Kura', 'Pulihora', 'Avakaya Biryani', 'Bobbatlu', 'Pootharekulu'],
    musicHighlights: ['Mangala Vadyam', 'Annamayya Kirtanas live ensemble', 'Tollywood live orchestra'],
    dressCodeSuggestion: 'Dharmavaram / Gadwal silk saree with temple ornaments, Silk Kurta and Pancha.',
    keyRituals: ['Pellikuthuru', 'Kanyadanam', 'Jeelakarra Bellam', 'Madhuparkam', 'Talambralu'],
  },
  'Kannada': {
    themeColor: '#751B29',
    secondaryColor: '#F5A623',
    accentColor: '#C9A227',
    greetingShloka: 'ಶುಭ ಸಮಾರಂಭಕ್ಕೆ ತಮಗೆಲ್ಲರಿಗೂ ಆದರದ ಸುಸ್ವಾಗತ',
    englishGreeting: 'Graceful traditions, sandalwood fragrance, and joyful familial celebrations.',
    recommendedDecor: 'Mysore sandalwood aesthetic, floral chandeliers, brass deepas, silk drapings.',
    specialDishes: ['Mysore Pak', 'Bisi Bele Bath', 'Obbattu (Holige)', 'Kosambari', 'Hayagreeva Sweet'],
    musicHighlights: ['Sugama Sangeetha', 'Nadaswara Vadana', 'Carnatic instrumental'],
    dressCodeSuggestion: 'Mysore Silk Saree with Traditional Kasuti work, Silk Dhoti with Zari Angavastra.',
    keyRituals: ['Nandi Puja', 'Kashi Yatre', 'Devarya Samaradhane', 'Dhare Herodu', 'Saptapadi'],
  },
  'Malayali': {
    themeColor: '#681A25',
    secondaryColor: '#F39C12',
    accentColor: '#D4AF37',
    greetingShloka: 'സ്വാഗതം | മംഗളകരമായ വിവാഹച്ചടങ്ങിലേക്ക് ഹൃദ്യമായ സ്വാഗതം',
    englishGreeting: 'Serene elegance, pure Kasavu weaves, and sacred Nilavilakku illuminations.',
    recommendedDecor: 'Nilavilakku lamps, coconut flower (Thengin Pookula) displays, jasmine & tulsi decor.',
    specialDishes: ['Grand Kerala Sadya on Plantain Leaf', 'Avial', 'Olan', 'Palada Payasam', 'Unniyappam'],
    musicHighlights: ['Chenda Melam', 'Nadaswaram', 'Sopana Sangeetham live melody'],
    dressCodeSuggestion: 'Kerala Kasavu Gold-bordered Mundum Neriyathum, Gold-bordered Jubba and Mundu.',
    keyRituals: ['Pennukanal', 'Nischayam', 'Madhuramveppu', 'Kanyadanam & Thalikettu', 'Kodi Uduthu'],
  },
  'Custom': {
    themeColor: '#7A1F2B',
    secondaryColor: '#F4A340',
    accentColor: '#C9A227',
    greetingShloka: 'सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके',
    englishGreeting: 'Crafted with elegance, love, and vibrant modern celebration.',
    recommendedDecor: 'Fusion floral mandap, geometric gold accents, bespoke fairy lighting.',
    specialDishes: ['Pan-Indian Culinary Platter', 'Live Chaat & Gourmet Counters', 'Dessert Carousel'],
    musicHighlights: ['Live Acoustic Fusion Band', 'DJ & Percussionist'],
    dressCodeSuggestion: 'Indo-Western Couture, Traditional Silk & Linen festive attire.',
    keyRituals: ['Welcome Address', 'Ceremonial Blessing', 'Ring Exchange / Rituals', 'Gala Dinner'],
  },
};

export const DEFAULT_BUDGET_RATIOS: Record<string, number> = {
  venue: 0.28,
  catering: 0.32,
  decoration: 0.16,
  photography: 0.08,
  entertainment: 0.06,
  invitation: 0.02,
  transportation: 0.03,
  contingency: 0.05,
};

export const DEFAULT_CHECKLIST_TEMPLATES: Record<EventType, Array<{ title: string; category: string }>> = {
  Wedding: [
    { title: 'Finalize Event Date & Auspicious Muhurtham', category: 'Planning' },
    { title: 'Select & Book Main Wedding Venue and Rooms', category: 'Venue' },
    { title: 'Choose Cultural Theme and Floral Mandap Design', category: 'Decoration' },
    { title: 'Select Catering Menu (Welcome Drinks, Starters, Main Feast)', category: 'Catering' },
    { title: 'Hire Professional Photographer & Cinematic Videographer', category: 'Media' },
    { title: 'Book Traditional Shehnai / Nadaswaram & Live DJ Band', category: 'Entertainment' },
    { title: 'Design Digital Indian Invitation & Send QR Passes', category: 'Guests' },
    { title: 'Arrange Bride & Groom Traditional Outfits & Jewelry', category: 'Wardrobe' },
    { title: 'Finalize 2D Seating & Table Allocations for VIPs', category: 'Layout' },
    { title: 'Configure Live Stream URL for Remote Relatives', category: 'Streaming' },
    { title: 'Verify Gateway Payments & Vendor Advance Settlements', category: 'Finance' },
    { title: 'Conduct Final Venue Gate Scanner Dry Run', category: 'Operations' },
  ],
  Engagement: [
    { title: 'Select Engagement Venue or Banquet Hall', category: 'Venue' },
    { title: 'Order Rings & Ceremonial Trays', category: 'Ceremony' },
    { title: 'Select Stage Floral Ring-Exchange Backdrop', category: 'Decoration' },
    { title: 'Finalize Dinner & Mocktail Buffet', category: 'Catering' },
    { title: 'Send Digital Save-the-Date Cards', category: 'Guests' },
    { title: 'Hire Candid Photographer', category: 'Media' },
  ],
  Birthday: [
    { title: 'Select Theme (Bollywood, Royal, Kids Fantasy)', category: 'Theme' },
    { title: 'Book Venue or Party Hall', category: 'Venue' },
    { title: 'Order Custom 3D Cake & Dessert Table', category: 'Catering' },
    { title: 'Arrange Balloon & Fairy Light Decor', category: 'Decoration' },
    { title: 'Hire Anchor / Magician / DJ', category: 'Entertainment' },
    { title: 'Send QR Invitations to Friends & Family', category: 'Guests' },
  ],
  Reception: [
    { title: 'Book Grand Reception Lawn or Ballroom', category: 'Venue' },
    { title: 'Design Royal Stage & Lighting SFX', category: 'Decoration' },
    { title: 'Arrange Multi-Cuisine Dinner Buffet & Live Counters', category: 'Catering' },
    { title: 'Hire Live Band & Symphony Orchestra', category: 'Entertainment' },
    { title: 'Setup Photo Booth with Instant Prints', category: 'Media' },
  ],
  Housewarming: [
    { title: 'Perform Vastu Shanti / Ganapathi Havan Schedule', category: 'Ritual' },
    { title: 'Decorate Entrance with Mango Leaves & Fresh Marigold Toran', category: 'Decoration' },
    { title: 'Arrange Traditional Satvik / Festive Lunch', category: 'Catering' },
    { title: 'Send Auspicious Gruhapravesham Invitations', category: 'Guests' },
  ],
  'Baby Shower': [
    { title: 'Plan Traditional Seemantham / Godh Bharai Ceremony', category: 'Ritual' },
    { title: 'Floral Swing & Pastel Balloon Decor Setup', category: 'Decoration' },
    { title: 'Curate Traditional Sweets & High-Tea Menu', category: 'Catering' },
    { title: 'Arrange Festive Music & Return Gifts', category: 'Entertainment' },
  ],
  'Naming Ceremony': [
    { title: 'Prepare Cradle & Fresh Floral Garland Canopy', category: 'Decoration' },
    { title: 'Schedule Priest for Namakarana Puja', category: 'Ritual' },
    { title: 'Arrange Festive Buffet for Relatives', category: 'Catering' },
    { title: 'Send Digital Baby Blessing Cards', category: 'Guests' },
  ],
  'Traditional Ceremony': [
    { title: 'Arrange Sacred Samagri & Decorate Altar', category: 'Ritual' },
    { title: 'Setup Fresh Marigold & Banana Leaf Canopy', category: 'Decoration' },
    { title: 'Organize Traditional Festive Prasad & Meals', category: 'Catering' },
    { title: 'Send Auspicious Event Invitations', category: 'Guests' },
  ],
  'Corporate Event': [
    { title: 'Book Convention Center or 5-Star Conference Hall', category: 'Venue' },
    { title: 'Setup Audio-Visual Systems, LED Walls & Podium', category: 'AV Tech' },
    { title: 'Arrange Corporate Luncheon & Hi-Tea Networking', category: 'Catering' },
    { title: 'Send Registration Passes with QR Code Badges', category: 'Operations' },
    { title: 'Configure Live Stream for Global Remote Employees', category: 'Streaming' },
  ],
  'College Event': [
    { title: 'Book Auditorium or Open-Air Amphitheatre', category: 'Venue' },
    { title: 'Hire Sound Systems, Truss & Stage Lighting', category: 'Equipment' },
    { title: 'Book Celebrity DJ or College Rock Band', category: 'Entertainment' },
    { title: 'Manage Student Passes & QR Entry Scanning', category: 'Security' },
  ],
  'Festival': [
    { title: 'Setup Community Pandal / Stage', category: 'Infrastructure' },
    { title: 'Arrange Cultural Dance & Drama Performances', category: 'Cultural' },
    { title: 'Organize Community Feast (Maha Prasadam / Langar)', category: 'Catering' },
    { title: 'Coordinate Security, Crowd Management & First Aid', category: 'Safety' },
  ],
  'Religious Event': [
    { title: 'Coordinate with Temple / Priests for Samagri', category: 'Ritual' },
    { title: 'Traditional Rangoli & Diya Floral Installations', category: 'Decoration' },
    { title: 'Arrange Pure Satvik Prasadam Distribution', category: 'Catering' },
    { title: 'Bhajan & Kirtan Musical Troupe Setup', category: 'Music' },
  ],
  Anniversary: [
    { title: 'Book Romantic Rooftop or Heritage Courtyard', category: 'Venue' },
    { title: 'Fairy Light Canopy & Candlelight Floral Tables', category: 'Decoration' },
    { title: 'Curate 4-Course Fine Dining & Wine/Mocktail Bar', category: 'Catering' },
    { title: 'Play Memory Lane Video & Slideshow', category: 'Media' },
  ],
  'Private Party': [
    { title: 'Select Private Villa or Poolside Venue', category: 'Venue' },
    { title: 'Setup Theme Lighting & Cocktail Lounge Decor', category: 'Decoration' },
    { title: 'Hire DJ & Live Grill Barbeque Counter', category: 'Catering' },
  ],
  Other: [
    { title: 'Define Event Objectives & Milestone Timeline', category: 'Planning' },
    { title: 'Select Venue & Finalize Guest Capacity', category: 'Venue' },
    { title: 'Arrange Custom Catering & Refreshments', category: 'Catering' },
    { title: 'Send Digital Passes & Manage Check-ins', category: 'Guests' },
  ],
};

export const INDIAN_EVENT_TYPES = [
  { type: 'Wedding', name: 'Royal Indian Wedding (विवाह)', icon: '💍', description: 'Grand multi-day celebration with Mandap, Sangeet, and 7 sacred Pheras.' },
  { type: 'Engagement', name: 'Engagement & Roka (सगाई)', icon: '✨', description: 'Ring ceremony, floral backdrops, and cocktail banquet.' },
  { type: 'Reception', name: 'Grand Gala Reception (स्वागत समारोह)', icon: '👑', description: 'Post-wedding grand feast with live symphony orchestra.' },
  { type: 'Housewarming', name: 'Griha Pravesh & Puja (गृह प्रवेश)', icon: '🪔', description: 'Auspicious Vastu havan, toran decor, and Satvik bhojan.' },
  { type: 'Birthday', name: 'Birthday Bash & Milestone (जन्मदिन)', icon: '🎂', description: 'Themed decor, 3D cakes, entertainment, and live counters.' },
  { type: 'Baby Shower', name: 'Godh Bharai & Baby Shower (गोद भराई)', icon: '🌸', description: 'Traditional blessings, floral swings, and family feast.' },
  { type: 'Traditional Ceremony', name: 'Sacred Samskara & Puja (धार्मिक अनुष्ठान)', icon: '🕉️', description: 'Upanayana, Satyanarayan Katha, and Vedic havans.' },
  { type: 'Corporate Event', name: 'Corporate Conclave & Gala (कॉर्पोरेट उत्सव)', icon: '🏢', description: 'Conferences, awards night, and executive networking.' },
  { type: 'Festival', name: 'Diwali & Festive Mela (त्यौहार)', icon: '🎆', description: 'Community pandals, Dandiya raas, and Diwali melas.' },
];

export const INDIAN_TRADITIONS = CULTURAL_TRADITIONS.map((name, idx) => ({
  id: `trad-${idx + 1}`,
  name,
  shloka: CULTURAL_THEMES_METADATA[name]?.greetingShloka || '|| शुभ लाभ ||',
  description: CULTURAL_THEMES_METADATA[name]?.englishGreeting || `${name} auspicious celebrations.`,
  decor: CULTURAL_THEMES_METADATA[name]?.recommendedDecor,
  dishes: CULTURAL_THEMES_METADATA[name]?.specialDishes,
}));

