import { IEvent } from './types';

export const SAMPLE_SHOWCASE_EVENTS: IEvent[] = [
  // =========================================================================
  // 1. 🎓 EDUCATION & COLLEGE EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000101',
    eventId: 'EVT-BIT-TECHFEST-2026',
    name: 'College Tech Fest 2026 & AI Hackathon',
    category: 'Education & College',
    subcategory: 'Technical Fest',
    type: 'Tech Meet & Hackathon',
    eventType: 'OFFLINE',
    institutionName: 'Bangalore Institute of Technology',
    department: 'Computer Science & Engineering',
    academicYear: '2026-2027',
    culturalTradition: 'Custom',
    date: '2026-09-18',
    startTime: '09:00 AM',
    endTime: '06:00 PM',
    location: {
      address: 'BIT Main Auditorium & Innovation Lab, VV Puram',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560004',
      latitude: 12.9499,
      longitude: 77.5753,
    },
    guestCount: 650,
    capacity: 800,
    availableSeats: 245,
    registeredCount: 555,
    budget: 450000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'AI Innovation, Robotics Arena & 24H Hackathon',
    description: 'Flagship inter-college technical festival featuring AI/ML coding sprints, Robowars, Project Expositions, Drone obstacle leagues, and cash prizes worth ₹3 Lakhs.',
    organizerName: 'BIT Tech Club & IEEE Student Branch',
    bannerImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.4,
  },
  {
    _id: '65d000000000000000000102',
    eventId: 'EVT-MYS-AIWORKSHOP-2026',
    name: 'AI & Machine Learning Hands-On Workshop',
    category: 'Education & College',
    subcategory: 'Workshop',
    type: 'College Event',
    eventType: 'OFFLINE',
    institutionName: 'National Institute of Engineering (NIE)',
    department: 'Data Science & AI',
    date: '2026-09-22',
    startTime: '10:00 AM',
    endTime: '05:00 PM',
    location: {
      address: 'NIE Diamond Jubilee Hall, Manandavadi Road',
      city: 'Mysuru',
      state: 'Karnataka',
      pincode: '570008',
      latitude: 12.2858,
      longitude: 76.6385,
    },
    guestCount: 300,
    capacity: 350,
    availableSeats: 78,
    registeredCount: 272,
    budget: 200000,
    price: 299,
    ticketPrice: 299,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Generative AI & Real-World Agentic Workflows',
    description: 'Intensive full-day practical workshop on building LLM agents, RAG pipelines, and deep neural models with certified industry mentors from DeepMind and Google.',
    organizerName: 'NIE Center for Artificial Intelligence',
    bannerImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 4.1,
  },
  {
    _id: '65d000000000000000000103',
    eventId: 'EVT-RVCE-HACK-2026',
    name: 'All-India Inter-University 36H Hackathon',
    category: 'Education & College',
    subcategory: 'Hackathon',
    type: 'Tech Meet & Hackathon',
    eventType: 'OFFLINE',
    institutionName: 'RV College of Engineering',
    department: 'Center for Innovation & Entrepreneurship',
    date: '2026-10-08',
    startTime: '08:00 AM',
    endTime: '08:00 PM',
    location: {
      address: 'RVCE Campus, Mysore Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560059',
      latitude: 12.9237,
      longitude: 77.4987,
    },
    guestCount: 500,
    capacity: 600,
    availableSeats: 110,
    registeredCount: 490,
    budget: 600000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Smart Cities, Climate Tech & Healthcare AI',
    description: 'Premier national collegiate hackathon with free meals, energy drinks, fast Wi-Fi, hardware kits, and VC on-spot seed grant funding for the top 5 teams.',
    organizerName: 'RVCE Developer Student Club',
    bannerImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 8.5,
  },
  {
    _id: '65d000000000000000000104',
    eventId: 'EVT-STPAUL-GRAD-2026',
    name: 'St. Paul Academy Annual Convocation & Graduation Gala',
    category: 'Education & College',
    subcategory: 'Graduation Ceremony',
    type: 'College Event',
    eventType: 'OFFLINE',
    institutionName: 'St. Paul Heritage Academy',
    date: '2026-11-12',
    startTime: '04:00 PM',
    endTime: '08:30 PM',
    location: {
      address: 'St. Paul Grand Quadrangle',
      city: 'Hubballi',
      state: 'Karnataka',
      pincode: '580020',
      latitude: 15.3647,
      longitude: 75.1240,
    },
    guestCount: 1200,
    capacity: 1500,
    availableSeats: 300,
    registeredCount: 900,
    budget: 350000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'PLANNING',
    theme: 'Academic Honors & Alumni Induction',
    description: 'Ceremonial conferral of diplomas and merit medals with chancellor address, musical orchestra, and commemorative graduation photography.',
    organizerName: 'St. Paul Academic Council',
    bannerImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 12.0,
  },
  {
    _id: '65d000000000000000000105',
    eventId: 'EVT-STATE-CAMPUS-FAIR-2026',
    name: 'Karnataka State Campus Placement & Career Fair',
    category: 'Education & College',
    subcategory: 'Placement Drive',
    type: 'College Event',
    eventType: 'OFFLINE',
    institutionName: 'State Higher Education Council',
    date: '2026-10-28',
    startTime: '09:00 AM',
    endTime: '05:30 PM',
    location: {
      address: 'Palace Grounds, Princess Shrine Gate 9',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560006',
      latitude: 13.0035,
      longitude: 77.5891,
    },
    guestCount: 3500,
    capacity: 4000,
    availableSeats: 650,
    registeredCount: 2850,
    budget: 800000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Connecting 120+ Top Tech Companies with Graduates',
    description: 'Mega hiring drive with Infosys, Wipro, TCS, Amazon, and 80+ hyper-growth startups interviewing engineering, commerce, and science graduates on spot.',
    organizerName: 'Karnataka Skill Development Mission',
    bannerImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 3.2,
  },

  // =========================================================================
  // 2. 💼 CORPORATE & BUSINESS EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000201',
    eventId: 'EVT-BLR-BIZSUMMIT-2026',
    name: 'Bengaluru Business Summit 2026',
    category: 'Corporate & Business',
    subcategory: 'Business Conference',
    type: 'Corporate Event',
    eventType: 'OFFLINE',
    date: '2026-09-25',
    startTime: '09:00 AM',
    endTime: '06:00 PM',
    location: {
      address: 'ITC Gardenia Grand Ballroom, Residency Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560025',
      latitude: 12.9674,
      longitude: 77.5968,
    },
    guestCount: 500,
    capacity: 600,
    availableSeats: 145,
    registeredCount: 455,
    budget: 1500000,
    price: 999,
    ticketPrice: 999,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'AI Enterprise Transformation & Global Growth Markets',
    description: 'Premier business leadership summit convening 50+ CXOs, unicorns founders, and international trade ambassadors for keynote dialogues and B2B matchmaking.',
    organizerName: 'Karnataka Chamber of Commerce & Industry',
    bannerImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 1.8,
  },
  {
    _id: '65d000000000000000000202',
    eventId: 'EVT-STARTUP-VCMEET-2026',
    name: 'National Startup Founders & VC Investor Meet',
    category: 'Corporate & Business',
    subcategory: 'Investor Meet',
    type: 'Startup Conclave',
    eventType: 'OFFLINE',
    date: '2026-10-15',
    startTime: '10:00 AM',
    endTime: '07:00 PM',
    location: {
      address: 'The Leela Palace Convention Center, Old Airport Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560008',
      latitude: 12.9606,
      longitude: 77.6484,
    },
    guestCount: 350,
    capacity: 400,
    availableSeats: 62,
    registeredCount: 338,
    budget: 1200000,
    price: 1499,
    ticketPrice: 1499,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Seed to Series-B Fundraising & Pitch Arena',
    description: 'Direct 1-on-1 curated meetings with Sequoia, Accel, Nexus, and Matrix Partners. Live pitch rounds with ₹10 Crore committed syndicate investment pool.',
    organizerName: 'India Venture Network',
    bannerImage: 'https://images.unsplash.com/photo-1559223607-a43c990c692c?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 5.6,
  },
  {
    _id: '65d000000000000000000203',
    eventId: 'EVT-FINTECH-EXPO-2026',
    name: 'Fintech & Digital India Leadership Expo 2026',
    category: 'Corporate & Business',
    subcategory: 'Trade Expo',
    type: 'Corporate Event',
    eventType: 'OFFLINE',
    date: '2026-11-04',
    startTime: '09:30 AM',
    endTime: '06:30 PM',
    location: {
      address: 'BIEC International Exhibition Centre, Tumkur Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '562123',
      latitude: 13.0617,
      longitude: 77.4752,
    },
    guestCount: 2000,
    capacity: 2500,
    availableSeats: 480,
    registeredCount: 2020,
    budget: 2200000,
    price: 799,
    ticketPrice: 799,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'UPI 2.0, CBDC, Open Banking & Cross-Border Rails',
    description: 'Over 150 leading fintech exhibitors displaying next-gen payments infrastructure, fraud prevention engines, and regulatory compliance tools.',
    organizerName: 'Fintech Association of India',
    bannerImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 14.2,
  },
  {
    _id: '65d000000000000000000204',
    eventId: 'EVT-AI-PRODUCT-LAUNCH-2026',
    name: 'NextGen AI Enterprise Product Launch & Keynote',
    category: 'Corporate & Business',
    subcategory: 'Product Launch',
    type: 'Product Launch',
    eventType: 'OFFLINE',
    date: '2026-10-22',
    startTime: '05:00 PM',
    endTime: '09:00 PM',
    location: {
      address: 'Taj West End Garden Amphitheatre, Race Course Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9833,
      longitude: 77.5833,
    },
    guestCount: 300,
    capacity: 350,
    availableSeats: 45,
    registeredCount: 305,
    budget: 950000,
    price: 499,
    ticketPrice: 499,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Unveiling Autonomous Enterprise Workforce Engine',
    description: 'Live product reveal, interactive tech demo pods, high-tea networking banquet, and exclusive VIP access to early developer SDKs.',
    organizerName: 'Cognitive Matrix Labs',
    bannerImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.1,
  },
  {
    _id: '65d000000000000000000205',
    eventId: 'EVT-AGILE-TECHLEAD-2026',
    name: 'Enterprise Tech Leadership & Strategy Conclave',
    category: 'Corporate & Business',
    subcategory: 'Leadership Conference',
    type: 'Corporate Event',
    eventType: 'OFFLINE',
    date: '2026-11-26',
    startTime: '09:00 AM',
    endTime: '05:00 PM',
    location: {
      address: 'JW Marriott Hotel, Vittal Mallya Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9719,
      longitude: 77.5937,
    },
    guestCount: 250,
    capacity: 300,
    availableSeats: 50,
    registeredCount: 250,
    budget: 1100000,
    price: 1299,
    ticketPrice: 1299,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Scaling Engineering Orgs in the Era of Agentic AI',
    description: 'Executive roundtable discussions for VPs of Engineering and CTOs on system architecture resiliency, security, and developer velocity.',
    organizerName: 'Global Tech Leaders Forum',
    bannerImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 1.5,
  },

  // =========================================================================
  // 3. 🎭 CULTURAL & ENTERTAINMENT EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000301',
    eventId: 'EVT-MYS-CULTURAL-NIGHT-2026',
    name: 'Mysuru Cultural Night & Sangeet Utsav',
    category: 'Cultural & Entertainment',
    subcategory: 'Cultural Festival',
    type: 'Cultural Fest',
    eventType: 'OFFLINE',
    culturalTradition: 'Kannada',
    date: '2026-10-02',
    startTime: '06:00 PM',
    endTime: '11:00 PM',
    location: {
      address: 'Mysuru Palace Grounds & Royal Durbar Stage',
      city: 'Mysuru',
      state: 'Karnataka',
      pincode: '570001',
      latitude: 12.3052,
      longitude: 76.6552,
    },
    guestCount: 2500,
    capacity: 3000,
    availableSeats: 480,
    registeredCount: 2520,
    budget: 1800000,
    price: 499,
    ticketPrice: 499,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Classical Carnatic Fusion, Yakshagana & Laser Spectacle',
    description: 'Royal palace evening illuminated by 100,000 golden bulbs featuring world-renowned Carnatic vocalists, Yakshagana theatrical troupes, and traditional Mysore cuisine.',
    organizerName: 'Karnataka Department of Kannada & Culture',
    bannerImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 3.5,
  },
  {
    _id: '65d000000000000000000302',
    eventId: 'EVT-SUFI-MUSIC-FEST-2026',
    name: 'Sufi & Bollywood Live Music Festival',
    category: 'Cultural & Entertainment',
    subcategory: 'Music Festival',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-10-24',
    startTime: '06:30 PM',
    endTime: '11:30 PM',
    location: {
      address: 'Manpho Convention Grounds, Manyata Tech Park Ring Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560045',
      latitude: 13.0458,
      longitude: 77.6200,
    },
    guestCount: 4000,
    capacity: 5000,
    availableSeats: 720,
    registeredCount: 4280,
    budget: 2500000,
    price: 750,
    ticketPrice: 750,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Soulful Qawwali, Acoustic Bollywood & Dhol Symphony',
    description: 'An enchanting musical evening with headliner performances by renowned Bollywood playback stars, live percussionists, and a vibrant food truck village.',
    organizerName: 'Sangeet Waves Entertainment',
    bannerImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 7.2,
  },
  {
    _id: '65d000000000000000000303',
    eventId: 'EVT-NATYA-DANCE-2026',
    name: 'All-India Classical Natyashastra Dance Gala',
    category: 'Cultural & Entertainment',
    subcategory: 'Dance Festival',
    type: 'Cultural Fest',
    eventType: 'OFFLINE',
    culturalTradition: 'South Indian',
    date: '2026-11-08',
    startTime: '05:30 PM',
    endTime: '09:30 PM',
    location: {
      address: 'Chowdiah Memorial Hall, Malleshwaram',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560003',
      latitude: 13.0068,
      longitude: 77.5794,
    },
    guestCount: 800,
    capacity: 1000,
    availableSeats: 150,
    registeredCount: 850,
    budget: 500000,
    price: 350,
    ticketPrice: 350,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Bharatanatyam, Kathak & Odissi Master Recitals',
    description: 'Mesmerizing classical dance performances by senior gurus and national youth prodigies accompanied by live flute, mridangam, and nattuvangam.',
    organizerName: 'Nritya Kala Kendra Bangalore',
    bannerImage: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 3.8,
  },
  {
    _id: '65d000000000000000000304',
    eventId: 'EVT-BLR-COMEDY-NIGHT-2026',
    name: 'Bangalore Stand-Up Comedy Showcase',
    category: 'Cultural & Entertainment',
    subcategory: 'Comedy Show',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-09-30',
    startTime: '07:30 PM',
    endTime: '10:00 PM',
    location: {
      address: 'Good Shepherd Auditorium, Museum Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560025',
      latitude: 12.9669,
      longitude: 77.6033,
    },
    guestCount: 600,
    capacity: 700,
    availableSeats: 90,
    registeredCount: 610,
    budget: 400000,
    price: 499,
    ticketPrice: 499,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Hilarious City Life, Tech Humor & Observational Laughs',
    description: 'An evening of non-stop humor featuring 5 top Indian stand-up comedians with fresh, hilarious specials about Bangalore traffic, tech startups, and Indian families.',
    organizerName: 'Laughter Therapy India',
    bannerImage: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.2,
  },
  {
    _id: '65d000000000000000000305',
    eventId: 'EVT-HANDICRAFT-FAIR-2026',
    name: 'All-India Artisans & Handicraft Heritage Mela',
    category: 'Cultural & Entertainment',
    subcategory: 'Handicraft Exhibition',
    type: 'Cultural Fest',
    eventType: 'OFFLINE',
    date: '2026-11-15',
    startTime: '10:00 AM',
    endTime: '08:30 PM',
    location: {
      address: 'ChitraKala Parishath, Kumara Krupa Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9897,
      longitude: 77.5828,
    },
    guestCount: 1500,
    capacity: 2000,
    availableSeats: 350,
    registeredCount: 1650,
    budget: 600000,
    price: 150,
    ticketPrice: 150,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Terracotta, Channapatna Toys, Mysore Silks & Madhubani Art',
    description: 'Celebrating 200+ master craftsmen with live pottery wheels, handmade wooden toys, brass sculptures, handloom weavers, and regional folk snacks.',
    organizerName: 'Karnataka Crafts Development Trust',
    bannerImage: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.9,
  },

  // =========================================================================
  // 4. 🏏 SPORTS & ATHLETICS EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000401',
    eventId: 'EVT-CRICKET-CUP-2026',
    name: 'Inter-College Cricket Cup 2026',
    category: 'Sports',
    subcategory: 'Cricket Tournament',
    type: 'College Event',
    eventType: 'OFFLINE',
    institutionName: 'Karnataka University Sports Board',
    date: '2026-10-05',
    startTime: '08:00 AM',
    endTime: '06:00 PM',
    location: {
      address: 'Chinnaswamy Stadium B-Ground, Queens Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9788,
      longitude: 77.5996,
    },
    guestCount: 1200,
    capacity: 1500,
    availableSeats: 280,
    registeredCount: 1220,
    budget: 900000,
    price: 300,
    ticketPrice: 300,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: '32 Teams Knockout Championship & Trophy Gala',
    description: 'High-octane T20 cricket tournament featuring Karnataka’s top collegiate teams. Live boundary commentary, food stalls, and celebrity cricketer felicitation.',
    organizerName: 'Bengaluru Youth Sports Council',
    bannerImage: 'https://images.unsplash.com/photo-1531415074868-036b1c5f53ec?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 1.9,
  },
  {
    _id: '65d000000000000000000402',
    eventId: 'EVT-BLR-10K-MARATHON-2026',
    name: 'Bengaluru City 10K Marathon & Fitness Run',
    category: 'Sports',
    subcategory: 'Marathon',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-10-18',
    startTime: '05:30 AM',
    endTime: '11:00 AM',
    location: {
      address: 'Kanteerava Outdoor Stadium, Kasturba Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9698,
      longitude: 77.5929,
    },
    guestCount: 5000,
    capacity: 6000,
    availableSeats: 850,
    registeredCount: 5150,
    budget: 2000000,
    price: 499,
    ticketPrice: 499,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Run for Clean Air & Green Bengaluru',
    description: 'Scenic 10K and 5K run passing through green Cubbon Park and Vidhana Soudha. Includes official dry-fit running jersey, RFID timing chip, breakfast buffet, and finisher medal.',
    organizerName: 'Bengaluru Runners Guild',
    bannerImage: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 1.1,
  },
  {
    _id: '65d000000000000000000403',
    eventId: 'EVT-BADMINTON-CHAMP-2026',
    name: 'Karnataka State Badminton Open Championship',
    category: 'Sports',
    subcategory: 'Badminton Championship',
    type: 'College Event',
    eventType: 'OFFLINE',
    date: '2026-11-01',
    startTime: '08:30 AM',
    endTime: '07:00 PM',
    location: {
      address: 'Padukone-Dravid Centre for Sports Excellence',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '562157',
      latitude: 13.1601,
      longitude: 77.6258,
    },
    guestCount: 600,
    capacity: 800,
    availableSeats: 120,
    registeredCount: 680,
    budget: 650000,
    price: 350,
    ticketPrice: 350,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Men, Women & Mixed Doubles Open Trophies',
    description: 'State ranking tournament played on 16 BWF-approved synthetic indoor courts with electronic line tracking and Yonex tournament shuttlecocks.',
    organizerName: 'Karnataka Badminton Association',
    bannerImage: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 16.5,
  },
  {
    _id: '65d000000000000000000404',
    eventId: 'EVT-KABADDI-LEAGUE-2026',
    name: 'All-India Inter-State Kabaddi Trophy 2026',
    category: 'Sports',
    subcategory: 'Kabaddi Tournament',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-11-14',
    startTime: '04:00 PM',
    endTime: '10:00 PM',
    location: {
      address: 'Koramanagala Indoor Stadium, 80 Feet Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560095',
      latitude: 12.9352,
      longitude: 77.6245,
    },
    guestCount: 2000,
    capacity: 2500,
    availableSeats: 350,
    registeredCount: 2150,
    budget: 1100000,
    price: 200,
    ticketPrice: 200,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Traditional Mud & Mat Super Raids Clash',
    description: 'Electrifying action featuring 16 top state teams battling with high-flying super tackles, raider bonus points, and live dhol commentary.',
    organizerName: 'Karnataka Kabaddi Federation',
    bannerImage: 'https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 4.8,
  },
  {
    _id: '65d000000000000000000405',
    eventId: 'EVT-ESPORTS-VALORANT-2026',
    name: 'Collegiate BGMI & Valorant Esports Championship',
    category: 'Sports',
    subcategory: 'Esports Tournament',
    type: 'Tech Meet & Hackathon',
    eventType: 'OFFLINE',
    date: '2026-10-31',
    startTime: '11:00 AM',
    endTime: '09:00 PM',
    location: {
      address: 'Phoenix Marketcity Courtyard Arena, Whitefield',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560048',
      latitude: 12.9961,
      longitude: 77.6961,
    },
    guestCount: 1500,
    capacity: 1800,
    availableSeats: 210,
    registeredCount: 1590,
    budget: 800000,
    price: 250,
    ticketPrice: 250,
    isFree: false,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: '64 Teams LAN Finals with 4K LED Screen Casters',
    description: 'The biggest gaming festival of the year with 240Hz gaming pods, shoutcasters, cosplay competitions, and ₹2 Lakh prize pool.',
    organizerName: 'Bengaluru Esports Guild',
    bannerImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 11.2,
  },

  // =========================================================================
  // 5. 💍 WEDDING & FAMILY EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000501',
    eventId: 'EVT-WEDDING-EXPO-2026',
    name: 'Grand Luxury Wedding & Bridal Expo 2026',
    category: 'Wedding & Family',
    subcategory: 'Wedding Expo',
    type: 'Corporate Event',
    eventType: 'OFFLINE',
    date: '2026-10-10',
    startTime: '10:00 AM',
    endTime: '08:00 PM',
    location: {
      address: 'Taj West End Grand Ballroom, Race Course Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9833,
      longitude: 77.5833,
    },
    guestCount: 1200,
    capacity: 1500,
    availableSeats: 320,
    registeredCount: 1180,
    budget: 1200000,
    price: 299,
    ticketPrice: 299,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Bridal Haute Couture, Mandap Architects & Royal Caterers',
    description: 'Explore 80+ leading Indian wedding designers, gold jewellery houses, heritage fort destinations, candid photographers, and luxury mandap architects.',
    organizerName: 'Virasat Wedding Guild India',
    bannerImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.1,
  },
  {
    _id: '65d000000000000000000502',
    eventId: 'EVT-RAJ-WED-2026',
    name: 'Royal Rajasthani Palace Wedding – Aarav & Ananya',
    category: 'Wedding & Family',
    subcategory: 'Wedding',
    type: 'Wedding',
    culturalTradition: 'Rajasthani',
    eventType: 'OFFLINE',
    date: '2026-11-20',
    startTime: '10:00 AM',
    endTime: '11:30 PM',
    location: {
      address: 'The Royal Haveli & Courtyard Lawns, Palace Road',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302001',
      latitude: 26.9124,
      longitude: 75.7873,
    },
    guestCount: 350,
    capacity: 400,
    availableSeats: 50,
    registeredCount: 350,
    budget: 1200000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Royal Rajputana Gold & Crimson Saat Phere',
    description: 'A grand royal celebration celebrating the union of Aarav and Ananya with authentic Rajputana traditions, Mewari gastronomy, and Shehnai welcoming.',
    organizerName: 'Shubh Utsav Planners',
    bannerImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 5.0,
  },
  {
    _id: '65d000000000000000000503',
    eventId: 'EVT-SOUTH-KALYANAM-2026',
    name: 'Traditional South Indian Kalyanam & Reception',
    category: 'Wedding & Family',
    subcategory: 'Wedding',
    type: 'Wedding',
    culturalTradition: 'Tamil',
    eventType: 'OFFLINE',
    date: '2026-11-28',
    startTime: '06:30 AM',
    endTime: '03:00 PM',
    location: {
      address: 'Gayathri Grand Kalyana Mandapam, Palace Grounds Gate 4',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560006',
      latitude: 13.0035,
      longitude: 77.5891,
    },
    guestCount: 600,
    capacity: 700,
    availableSeats: 60,
    registeredCount: 640,
    budget: 900000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Temple Gopuram Floral Mandap & 24-Course Banana Leaf Sadya',
    description: 'Auspicious Vedic Muhurtham, Kashi Yatra, Maalai Maatral, Oonjal swing ceremony, and traditional Madurai Malli jasmine decor.',
    organizerName: 'Dakshin Heritage Weddings',
    bannerImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 3.3,
  },
  {
    _id: '65d000000000000000000504',
    eventId: 'EVT-PUNJABI-SANGEET-2026',
    name: 'Grand Punjabi Sangeet Night & Dhol Celebration',
    category: 'Wedding & Family',
    subcategory: 'Sangeet',
    type: 'Wedding',
    culturalTradition: 'Punjabi',
    eventType: 'OFFLINE',
    date: '2026-12-05',
    startTime: '07:00 PM',
    endTime: '12:00 AM',
    location: {
      address: 'Manikshaw Convention Centre, MG Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9754,
      longitude: 77.6189,
    },
    guestCount: 450,
    capacity: 500,
    availableSeats: 45,
    registeredCount: 455,
    budget: 750000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'PLANNING',
    theme: 'Bhangra, Live Punjabi Dhol Troupes & Tandoori Feast',
    description: 'High-energy musical dance battle, choreographed family performances, live Amritsari Kulcha counters, and DJ Bollywood remix marathon.',
    organizerName: 'Amritsar Royal Planners',
    bannerImage: 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.8,
  },
  {
    _id: '65d000000000000000000505',
    eventId: 'EVT-SILVER-JUBILEE-2026',
    name: 'Silver Jubilee 25th Wedding Anniversary & Family Reunion',
    category: 'Wedding & Family',
    subcategory: 'Anniversary',
    type: 'Anniversary',
    culturalTradition: 'Custom',
    eventType: 'OFFLINE',
    date: '2026-12-18',
    startTime: '06:00 PM',
    endTime: '11:00 PM',
    location: {
      address: 'Windsor Manor Ballroom, Sankey Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560052',
      latitude: 12.9961,
      longitude: 77.5878,
    },
    guestCount: 200,
    capacity: 250,
    availableSeats: 25,
    registeredCount: 225,
    budget: 550000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'PLANNING',
    theme: 'Silver Elegance, Retro 90s Melodies & Photo Nostalgia Wall',
    description: 'A heartwarming 25-year milestone commemoration with vow renewals, memory slide show, live acoustic saxophonist, and 4-course banquet.',
    organizerName: 'Kapadia Family Trust',
    bannerImage: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 3.1,
  },

  // =========================================================================
  // 6. 🤝 COMMUNITY & SOCIAL EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000601',
    eventId: 'EVT-BLR-CHARITYRUN-2026',
    name: 'Bengaluru Charity Run 2026',
    category: 'Community & Social',
    subcategory: 'Charity Event',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-10-10',
    startTime: '06:00 AM',
    endTime: '10:30 AM',
    location: {
      address: 'Cubbon Park Bandstand & Green Corridor',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9763,
      longitude: 77.5929,
    },
    guestCount: 1500,
    capacity: 2000,
    availableSeats: 450,
    registeredCount: 1550,
    budget: 350000,
    price: 199,
    ticketPrice: 199,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Educating Underprivileged Rural Children',
    description: 'Join thousands of citizens running through the serene green tracks of Cubbon Park. 100% of registrations go directly to building school digital libraries in rural Karnataka.',
    organizerName: 'Rotary Club of Bangalore & Akshaya Patra',
    bannerImage: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 0.8,
  },
  {
    _id: '65d000000000000000000602',
    eventId: 'EVT-HEALTH-CAMP-2026',
    name: 'Voluntary Blood Donation & Free Health Screening Camp',
    category: 'Community & Social',
    subcategory: 'Blood Donation Camp',
    type: 'Religious Event',
    eventType: 'OFFLINE',
    date: '2026-10-20',
    startTime: '08:30 AM',
    endTime: '04:30 PM',
    location: {
      address: 'KMC Hospital Campus & Community Hall',
      city: 'Mangaluru',
      state: 'Karnataka',
      pincode: '575001',
      latitude: 12.8703,
      longitude: 74.8436,
    },
    guestCount: 400,
    capacity: 500,
    availableSeats: 120,
    registeredCount: 380,
    budget: 150000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Every Blood Drop Saves a Life',
    description: 'Free cardiac screening, diabetes tests, and blood donation certificates with nutrition packages in association with Indian Red Cross Society.',
    organizerName: 'Red Cross Society & Mangaluru Doctors Guild',
    bannerImage: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 9.0,
  },
  {
    _id: '65d000000000000000000603',
    eventId: 'EVT-TREE-PLANTATION-2026',
    name: 'Green Bengaluru 10,000 Tree Plantation Drive',
    category: 'Community & Social',
    subcategory: 'Tree Plantation Drive',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-11-07',
    startTime: '07:30 AM',
    endTime: '12:30 PM',
    location: {
      address: 'Turahalli Forest Eco Buffer Zone, Kanakapura Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560062',
      latitude: 12.8856,
      longitude: 77.5254,
    },
    guestCount: 800,
    capacity: 1000,
    availableSeats: 220,
    registeredCount: 780,
    budget: 200000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Native Saplings, Agro-Forestry & Urban Green Cover',
    description: 'Hands-on volunteer tree planting drive providing free saplings, gardening toolkits, compost, and refreshments for green volunteers.',
    organizerName: 'SayTrees & Karnataka Forest Dept',
    bannerImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 12.4,
  },
  {
    _id: '65d000000000000000000604',
    eventId: 'EVT-CLEANUP-DRIVE-2026',
    name: 'Lake Restoration & Community Cleanup Drive',
    category: 'Community & Social',
    subcategory: 'Environmental Campaign',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-11-21',
    startTime: '06:30 AM',
    endTime: '10:30 AM',
    location: {
      address: 'Agara Lake Wetland Promenade, HSR Layout',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560102',
      latitude: 12.9238,
      longitude: 77.6433,
    },
    guestCount: 500,
    capacity: 600,
    availableSeats: 110,
    registeredCount: 490,
    budget: 120000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Reviving Urban Water Bodies & Bio-Diversity',
    description: 'Community environmental drive to clean lake bunds, plant water-purifying reeds, and install bird nesting boxes.',
    organizerName: 'Bengaluru Lake Conservation Trust',
    bannerImage: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 6.8,
  },
  {
    _id: '65d000000000000000000605',
    eventId: 'EVT-WELLNESS-CIRCLE-2026',
    name: 'Youth Mental Health & Mindfulness Community Circle',
    category: 'Community & Social',
    subcategory: 'Community Meetup',
    type: 'Festival',
    eventType: 'OFFLINE',
    date: '2026-12-06',
    startTime: '04:00 PM',
    endTime: '07:00 PM',
    location: {
      address: 'Rangoli Metro Art Center, MG Road Boulevard',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9756,
      longitude: 77.6067,
    },
    guestCount: 200,
    capacity: 250,
    availableSeats: 60,
    registeredCount: 190,
    budget: 80000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Safe Spaces, Guided Sound Meditation & Expressive Art',
    description: 'An open, empathetic community circle guided by certified psychologists and sound bowl practitioners for stress relief and mindful journaling.',
    organizerName: 'MindCare Community Bangalore',
    bannerImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 1.6,
  },

  // =========================================================================
  // 7. 🛕 RELIGIOUS & TRADITIONAL EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000701',
    eventId: 'EVT-NAVRATRI-GARBA-2026',
    name: 'Maha Navratri Raas Garba Mahotsav 2026',
    category: 'Religious & Traditional',
    subcategory: 'Navratri Celebration',
    type: 'Festival',
    culturalTradition: 'Gujarati',
    eventType: 'OFFLINE',
    date: '2026-10-15',
    startTime: '07:30 PM',
    endTime: '02:00 AM',
    location: {
      address: 'Karnavati Club Arena & Lawns, SG Highway',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380058',
      latitude: 23.0225,
      longitude: 72.5015,
    },
    guestCount: 3500,
    capacity: 4000,
    availableSeats: 550,
    registeredCount: 3450,
    budget: 1800000,
    price: 250,
    ticketPrice: 250,
    isFree: false,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Chaniya Choli & 100-Piece Live Folk Orchestra',
    description: 'Grand Navratri Dandiya celebration featuring non-stop live traditional dhol, Aarti, authentic Gujarati street food counters, and prizes for best dancers.',
    organizerName: 'Gujarat Cultural Council',
    bannerImage: 'https://images.unsplash.com/photo-1603228254119-e6aefd84be25?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 6.0,
  },
  {
    _id: '65d000000000000000000702',
    eventId: 'EVT-GANESH-UTSAV-2026',
    name: 'Grand Ganesh Chaturthi Visarjan & Cultural Mahotsav',
    category: 'Religious & Traditional',
    subcategory: 'Ganesh Festival',
    type: 'Religious Event',
    culturalTradition: 'Marathi',
    eventType: 'OFFLINE',
    date: '2026-09-17',
    startTime: '09:00 AM',
    endTime: '10:00 PM',
    location: {
      address: 'APS Ground & Basavanagudi Temple Grounds',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560004',
      latitude: 12.9421,
      longitude: 77.5750,
    },
    guestCount: 5000,
    capacity: 6000,
    availableSeats: 800,
    registeredCount: 5200,
    budget: 1200000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: true,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Eco-Friendly Clay Ganesha, Nasik Dhol & Maha Prasadam',
    description: '30-foot clay Ganesha idol, sacred Vedic chants, 108 Dhol-Tasha artists, classical nadaswaram recital, and distribution of 10,000 Modaks.',
    organizerName: 'Bengaluru Sarvajanika Ganeshotsava Trust',
    bannerImage: 'https://images.unsplash.com/photo-1567591414240-e22d99d1469e?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.7,
  },
  {
    _id: '65d000000000000000000703',
    eventId: 'EVT-DIWALI-DEEPOTSAV-2026',
    name: 'Diwali Deepotsav & 1008 Diya Lighting Ceremony',
    category: 'Religious & Traditional',
    subcategory: 'Diwali Celebration',
    type: 'Religious Event',
    culturalTradition: 'North Indian',
    eventType: 'OFFLINE',
    date: '2026-11-01',
    startTime: '05:30 PM',
    endTime: '09:30 PM',
    location: {
      address: 'ISKCON Temple Quadrangle & Kalyani Pond, Rajajinagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560010',
      latitude: 13.0098,
      longitude: 77.5511,
    },
    guestCount: 2500,
    capacity: 3000,
    availableSeats: 350,
    registeredCount: 2650,
    budget: 650000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Sacred Ghee Diyas, Rangoli Mandala & Flower Showers',
    description: 'Spectacular twilight ceremony with 1008 floating earthen lamps on the temple Kalyani, soul-stirring Krishna bhajans, and distribution of pure ghee sweets.',
    organizerName: 'ISKCON Cultural Heritage Center',
    bannerImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 5.4,
  },
  {
    _id: '65d000000000000000000704',
    eventId: 'EVT-DASARA-RATHA-2026',
    name: 'Mysore Dasara Temple Ratha & Chamundeshwari Utsav',
    category: 'Religious & Traditional',
    subcategory: 'Temple Festival',
    type: 'Festival',
    culturalTradition: 'Kannada',
    eventType: 'OFFLINE',
    date: '2026-10-12',
    startTime: '08:00 AM',
    endTime: '08:00 PM',
    location: {
      address: 'Chamundi Hill Temple Steps & Main Sanctum',
      city: 'Mysuru',
      state: 'Karnataka',
      pincode: '570010',
      latitude: 12.2727,
      longitude: 76.6713,
    },
    guestCount: 4000,
    capacity: 5000,
    availableSeats: 600,
    registeredCount: 4400,
    budget: 1400000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Golden Howdah Elephant Procession & Mangala Aarti',
    description: 'Traditional procession of Goddess Chamundeshwari with decorated temple elephants, Nadaswaram ensembles, and temple chariot pulling.',
    organizerName: 'Chamundeshwari Temple Trust',
    bannerImage: 'https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 7.8,
  },
  {
    _id: '65d000000000000000000705',
    eventId: 'EVT-VEDIC-HAVAN-2026',
    name: 'Grand Vedic Maha Yagya & World Peace Chanting',
    category: 'Religious & Traditional',
    subcategory: 'Puja',
    type: 'Religious Event',
    culturalTradition: 'North Indian',
    eventType: 'OFFLINE',
    date: '2026-12-12',
    startTime: '07:00 AM',
    endTime: '01:30 PM',
    location: {
      address: 'Shankara Matha Heritage Hall, Shankarapuram',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560004',
      latitude: 12.9482,
      longitude: 77.5712,
    },
    guestCount: 600,
    capacity: 750,
    availableSeats: 110,
    registeredCount: 640,
    budget: 300000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    eventFormat: 'IN_PERSON',
    status: 'CONFIRMED',
    theme: 'Rudra Havan, Purusha Suktam & Vedic Chanting by 51 Pandits',
    description: 'Sacred fire ritual performed with 108 aromatic herbs and pure cow ghee for health, prosperity, and global harmony.',
    organizerName: 'Veda Vijnana Samithi',
    bannerImage: 'https://images.unsplash.com/photo-1608889825103-e55950c7494b?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 2.3,
  },

  // =========================================================================
  // 8. 🌐 ONLINE & HYBRID EVENTS (5+ Distinct Events)
  // =========================================================================
  {
    _id: '65d000000000000000000801',
    eventId: 'EVT-AI-CLOUD-WEBINAR-2026',
    name: 'AI & Cloud Computing Masterclass Webinar',
    category: 'Online & Hybrid',
    subcategory: 'Webinar',
    type: 'Tech Meet & Hackathon',
    eventType: 'ONLINE',
    eventFormat: 'ONLINE',
    date: '2026-10-15',
    time: '06:00 PM',
    startTime: '06:00 PM',
    endTime: '08:30 PM',
    location: {
      address: 'Live Stream via Zoom & Google Meet',
      city: 'Online',
      state: 'Global',
      pincode: '000000',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    guestCount: 3000,
    capacity: 5000,
    availableSeats: 1850,
    registeredCount: 3150,
    budget: 150000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: true,
    isLive: true,
    streamUrl: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
    meetingPlatform: 'Zoom Webinar Pro & YouTube Live',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Cloud Native Architecture, Kubernetes & Distributed AI',
    description: 'Learn modern cloud architecture and agentic AI deployments from senior staff engineers at Google Cloud. Live interactive Q&A and verified e-certificates provided.',
    organizerName: 'Cloud Native Developer Network',
    bannerImage: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 0.1,
  },
  {
    _id: '65d000000000000000000802',
    eventId: 'EVT-WEB3-VIRTUAL-HACK-2026',
    name: 'Global Web3 & Agentic AI Virtual Hackathon',
    category: 'Online & Hybrid',
    subcategory: 'Virtual Hackathon',
    type: 'Tech Meet & Hackathon',
    eventType: 'ONLINE',
    eventFormat: 'ONLINE',
    date: '2026-10-25',
    time: '10:00 AM',
    startTime: '10:00 AM',
    endTime: '10:00 PM',
    location: {
      address: 'Global Discord & Devpost Metaverse Arena',
      city: 'Online',
      state: 'Global',
      pincode: '000000',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    guestCount: 2500,
    capacity: 4000,
    availableSeats: 1200,
    registeredCount: 2800,
    budget: 600000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: true,
    isLive: true,
    streamUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
    meetingPlatform: 'Discord Metaverse & Devpost Arena',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Decentralized Autonomous Agents & ZK-Rollups',
    description: '48-hour global virtual sprint with $25,000 USD in crypto bounties, cloud credits, and accelerator fast-track for top 3 teams.',
    organizerName: 'Web3 Builders Guild',
    bannerImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 0.1,
  },
  {
    _id: '65d000000000000000000803',
    eventId: 'EVT-HYBRID-GROWTH-2026',
    name: 'Hybrid Digital Marketing & Growth Summit 2026',
    category: 'Online & Hybrid',
    subcategory: 'Hybrid Conference',
    type: 'Corporate Event',
    eventType: 'HYBRID',
    eventFormat: 'HYBRID',
    date: '2026-11-10',
    time: '09:30 AM',
    startTime: '09:30 AM',
    endTime: '06:00 PM',
    location: {
      address: 'WeWork Galaxy Auditorium & Virtual 4K Stream',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      latitude: 12.9754,
      longitude: 77.6054,
    },
    guestCount: 1200,
    capacity: 1500,
    availableSeats: 280,
    registeredCount: 1220,
    budget: 800000,
    price: 499,
    ticketPrice: 499,
    isFree: false,
    isFeatured: false,
    isLive: true,
    streamUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    meetingPlatform: 'Hopin Virtual Stage + Onsite Auditorium',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Performance Marketing, AI Creatives & Funnel Optimization',
    description: 'Attend in-person in Bangalore or join live from anywhere in the world with real-time interactive audience polling and backstage breakout rooms.',
    organizerName: 'Growth Hackers India',
    bannerImage: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 1.7,
  },
  {
    _id: '65d000000000000000000804',
    eventId: 'EVT-ONLINE-ASTRO-2026',
    name: 'Online Vedic Astroscience & Vastu Shastra Masterclass',
    category: 'Online & Hybrid',
    subcategory: 'Virtual Workshop',
    type: 'Religious Event',
    culturalTradition: 'North Indian',
    eventType: 'ONLINE',
    eventFormat: 'ONLINE',
    date: '2026-11-22',
    time: '07:00 PM',
    startTime: '07:00 PM',
    endTime: '09:30 PM',
    location: {
      address: 'Live Stream via Zoom Webcast',
      city: 'Online',
      state: 'Global',
      pincode: '000000',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    guestCount: 800,
    capacity: 1000,
    availableSeats: 160,
    registeredCount: 840,
    budget: 100000,
    price: 399,
    ticketPrice: 399,
    isFree: false,
    isFeatured: false,
    isLive: true,
    meetingPlatform: 'Zoom Webcast HD',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Planetary Alignments, Auspicious Muhurtham Calculation & Vastu',
    description: 'Learn ancient Jyotish calculations, planetary dasha interpretations, and energy harmonizing for modern homes and businesses.',
    organizerName: 'Vedic Wisdom Institute',
    bannerImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 0.1,
  },
  {
    _id: '65d000000000000000000805',
    eventId: 'EVT-GLOBAL-DIASPORA-2026',
    name: 'Global Indian Diaspora Virtual Summit & Networking',
    category: 'Online & Hybrid',
    subcategory: 'Online Seminar',
    type: 'Corporate Event',
    eventType: 'ONLINE',
    eventFormat: 'ONLINE',
    date: '2026-12-01',
    time: '08:00 PM',
    startTime: '08:00 PM',
    endTime: '11:00 PM',
    location: {
      address: 'Global Virtual Stage (USA, UK, Singapore, India)',
      city: 'Online',
      state: 'Global',
      pincode: '000000',
      latitude: 12.9716,
      longitude: 77.5946,
    },
    guestCount: 2000,
    capacity: 3000,
    availableSeats: 650,
    registeredCount: 2350,
    budget: 350000,
    price: 0,
    ticketPrice: 0,
    isFree: true,
    isFeatured: false,
    isLive: true,
    meetingPlatform: 'Virtual Global Auditorium Pro',
    certificateProvided: true,
    status: 'CONFIRMED',
    theme: 'Connecting NRI Leaders, Tech Entrepreneurs & Cultural Ambassadors',
    description: 'Connecting Indian diaspora professionals across Silicon Valley, London, Dubai, and Singapore to foster cross-border mentorship and cultural celebration.',
    organizerName: 'Overseas Indian Friends Association',
    bannerImage: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
    distanceKm: 0.1,
  },
];
